---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gami-secrets
  namespace: gami
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgCUERvSXQ6Uo2TcQCZLYPdXqw91KckletRlAKTltDLSFjlnJvx5l2R5O5L7h+Z7LiwGsLVjUiHEIu7TqorR7dDYJ49gTChWuB8ge78nT/IrP+4ykcKN+N8f52ERXFaW2NqD9dQmuEpFG8uyNMJo2TomY3rW9WbV8L/azdB3eY4DWLKkiD+LHPhbXQxaVsb+jvElYfpF8dLsCrHArtM9Vw5ooJ+fU/3RoHiixgL525tZgacfOoCWsUUHjdVXq32E5RZE3AmAb2FbD0x+UFIjbID53w2WNbqv1wiUCIS1w/baPS+3CZdrqClBaUFHKg9Nam8R6q9bEinuw7zOG0LrR/1dIlqo2hfOFCjwdHca/emggUbU05Zxua+7GLKHPmuzCIVpfekoqgUHBn8LeaXwhzaoxEB1anjVkThH61fdwLB2LBKHCDJeryPdTEGB0HS+J+6u88FcSA0KmcjDb/xViNTrTbBJP2BdkFcAcNtUIW6UC9pOAT7n0x+W2j97Htx0CEdr/HXW63WmrVa9lkn5EJyGM4zccm/eV1KGJXkQvQGwV3LGzKojR09Rj4Mw2ZXUtP5xdSjQkqEex1Aj76+n97S0cIUN+3nuMKiQQrocsGjDnUmEiUODvUhPPBPoG0xDz0rEsp9fQnJLB+E+KIlR6ojLpOiXs8DyOhQiiHhGfDYxQsFxuwBgWScwxSboqjaEBvoSUp+3o+CL54WmFtDTO/1/I6p3Xb26Y5vny1sVETMQSvz5WLIV0qKz152LoM9HBSA/uJBmoXOvBRuOh99LuJXS
  template:
    metadata:
      name: gami-secrets
      namespace: gami
