---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gami-secrets
  namespace: gami
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgB1SFIBDxTiVCVUFdMl3u89kP8W5N5DF3D+1MEcQ1NWMiv50CIT5oMktzSMLz+uFGd4jEIdAV7M6+vTXzC0dP/EVxEEc9n3hllCgJQ8EGhNrs4WYFUs+dZmS1WUlUDRa+hUH0rD5oeuiTkzv6ysCdrYfr+iNr4zlU+NQ+G61H7C+6uxywMTi4DO6IRlzrzDIVmnKyMmTZt7NXLWoDmibQ0yNGyYyimK6ecT+iwrPPiUQbRZH5ZaxTzFyx1TsZVeBlaJfOGViXCLjGBu5c0z0N4z/pxy7yVxpOkZh8NtIXnNNsQgPc2xtwpEy1VCzsJGgFAypAxCj9LK/aeaNhyw8Lnpafrxb2Q8Kr1f97Rqs+kCuw3POGbkQvP8bsLe68JahgGZrIEaleK0SKvLE3/pqtxzFBxFz7hCY6gHfdFgWRlp4VAIRkp1pyFun1ZKM3U7xHm+FjetaUdqG1V8WN/kp6u1Ogr/4yT1oDjlIHHbXNLIXXorfdYUsvmSTwK8Csl05MISvBVw+nbMjFlNnE1uH6gZ5WrYLQ3GfDMfvVH/hjWD3tng4PUnDWE6mw3Q3KtOY8x+eIdljf9SNpHb+HS9lls1jUForNjNQ/41Y/sJfByNAxLsv4ZV9WYKRnV2pm98haJLwGXcae0BhZIpz4hiugd7WeiMNOkWcbgSWf/GtjCnpus9UxblnHrM9lUJrqvsjqwbQvUSvq0G9hQZlNNT7lo3cTHBsnlYFJtKmmwP9Rs43S2awnK0+UYX/6upLbYm99DLztkkzK7b2Zys0ExG3dEv
  template:
    metadata:
      name: gami-secrets
      namespace: gami
