---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gami-smtp
  namespace: gami
spec:
  encryptedData:
    SMTP_PASS: AgBdGB7Ox322pgOQJg0vFCJ0lq0uL1gZ++2jw9HPzgFaJXNVYk2nFp8Wll1DMaiv06orehMGi/ZSo99YZoPTZx+2kVcuXLxh5z3wxPFlOhpnlTjNO5Sab4QtSOLoFxcPvgfJiab2MLblJpNgUNW9tfiPHYXKasuHFnpwJb+f4u4kp6AzYUlas2lDJkOA/W38m0CRo/QNQCW3QU+c9nVbsDeh1RAErJ09LPulYs5YP93ugy9oV7e3Afxn72YcyGDjx0GhN9DH1igCqJXwA3T0hrLqI9xK6Xsml/WLech97qrpGWh5YGWd5bgejV8s4YAJ9YZnp6sQl8DhFFLj+ui64zxJiHlAcjMBYj6hn/Y59AeWnWpuznzhrOD2GHcviIQk6I0134B3wDngpsNi56yS/sD7/e39Cp0mzc86rvOex8GY7yy4eWgJdljYZ5afFJ/dFjj24FMINesmtp80x6y9M6eO5I8Y3rsjnzrJojiN5WH6v/2VY5M1cDgy7le+WazCPYwPZmweKD8IfncU5DnrvjmxBGuSNtCOn2angMXke6M8Rn2VR4aC+SAuKI3Lr5ivTBIZ+DNi0E3O4NW56j4VL1Mrzscvf34b1Y/IikQzXn78RBxY3ta1h0n+yLT+o5GnSP7QgRWEfCuvH3t3ps14Y2hdnHDLmSDCaQoVaGzzYLxV7jl34mVqAdV0sCoWRRvRTgDeTcgMgSsyk4kX17zdN79Zan8e
    SMTP_USER: AgBQ3C6S/wR/IqNFVvi71lG05V+Uk3ktcnBz5PGLrb+a843S0zSLpglcqxsg02fOPF7r9WgwnoR6W2qJRxtxb3NUr4UVRLz3wocVcuqLpgKuM04IcJVAtsNAMK6KN946wszTbyboxl+7iQOcIRZIjBenEV2ioC5tGAA2bg/yGrQEK6hAvEYBR5SgPu4d2r9GpXFUAnWSCGJiQNTHX8nScYGFV+M0tL+ZHTmPqN1PfOX949x5AgNfzISrvm2SPuwMvTpf82bL7MDslJ1SuL+e/KTYDo7WPZcOM8lnIxjRREpkVPXyFvb7tsCWs/fg+6OUtwlh+VNAYOFDyj9gDX2zEVmwaHxhoDo2ZRTmsJn+1xGTPswcfniUn2u/uskFiN22jpXJeJ8xpdyxvr+G3TXJBBnak1QpDer5wABZzSYysp87fzCKxx8Dp/2HmJTRkd78VFSFAypNMi34RHkgekPLdftgEQBToFhm6zlGsJEN6yefWTsFkArntg3Rd48iiyxCwqipF29hHSIvHdFDCSREgOFTcLnQNfsmxGfUsVcf95kTTUli2ohU33LNf+Fh5qTU1ok3Z3CXDR3Xd7bfQf52Vn0qlp4M8LmOKqaY/wegkCN6CIBG6umV6AYVCkBc6a8ktG10PBxMCyHkDzmx7YlN2ENc1l441bu6cbO4DLAJ2oZwVBWk2XPGTyGmlxqnK7ome5prDHkA8vYluey7hSlZ49Yd5QHePeG/y6mL75I=
  template:
    metadata:
      name: gami-smtp
      namespace: gami
