---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gami-secrets
  namespace: gami-staging
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgAua6QXxOA4/3f3RbvjQIH4UHLeFMk+LwpdfXyB9zlF1SmTEJLcOGCysDcx6G6wuC5ixy6um/E4xF7fhBYOue7yfUf3zLRNul+KfVi2BiBVl7KqPBnMIbnQCOTkcceg1LEau265eqKAclp9J+3DY5Zm095kggvKTV+qI4uquCSOiSj7XzEHKGQVD1zPhr1Tyzm+aTadq5FITTK5il2nZPSKBojouAVdG5i1qu/QAizWsN2AVMsQSP0Ei6EmOsA3qqryXLzjIaUZ6t6izn0Dvnxbh8xu2WNt2RTWQYvZXKW/exFhmyN3tmJb0E5c6eG5lGjdgOHxAkc+2xhclRinvZ4Pbr+aqzN1uOTzDliVzAWcEkpLi406Ph2hlVgy7+K243+ED96PsApvipY+KBsNftgQO7uHy/C9KmcbYTeuOSPf7Jq6FAuY2SPflOXhHNyf0USqlzNNWxBzoQDixzV8jP7XKfp/7iq25ocmiAfXAK9cxGtdBn1dpuQ08wRzAdH9GvetxNGS1J4dJqs66LMTUlSihdHecCR18nvUCXmYSxhO1nJaT4Mv6g7WwIjkSn1dm0xmuVbpOWAKmpNekZ4Dhhc/+Bc8SgrJ7X3xRBfNaX3Xmj/bd72vbyN7sQKRcca4Nxh/6svOsNPPA7uxOv019DL+oYhy8pfYM5mgGv6+JMEehy37pFD8h0pMLz12hCQWew2zDAEcyXbFuy4ED70i2DhjLJ4gh/oy+osUAlgiNpkAoNhD5Lny7b+aE8os/2rzIXsldfJ0mRqtxjjFe3FPt1TH
  template:
    metadata:
      name: gami-secrets
      namespace: gami-staging
