---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gami-secrets
  namespace: gami-dev
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgBCaX/1V29Eyo3LWJx9uif8gWDZ7Ep2YqSqmKR1oZpyCCk75tMMws+1cXRFiBW7DfiEYnT7VE2FF0FruInGqx0k895EVKU4lw06wA3pOYNdt3gD0wy9DjXzUl1MMKWYSAgjtSij2rr4n+hfBGWuDsoG4VzJ2ejNSRQ4iFjFdnFiK1mSWzKunDa2okGC5fFHbMeBbLXlXdidjs4Al6kUys8oRE7rBa3/8KdyIm4QaEOh8DU6wdPxzGDP1T0LnJQ6/aHfq/pt2p1gCmkUZcjnIUoD1597Djrif+GAaBzamD7lNmBd6FedgRD/juRFTsXsHJtfknV+nna5ctxb1PbbQAdGAPKvL3od9VE+m6ECYQKBD9adbfNYZTk+35q00OR/5wnMXThPXGAAilvNqmKZm8p/BbNCdWxcx37Uximh/GhV40j63qO14PvxR4ORAtkqNb3ir8acqhcE6Zk/kO5JdM3fg+T+MayiXA2KZp7EvEL27RBdqSbYKn+Oaj7ciYyDEMXxxYmKNp3eOD1Jr2vpKc5PKyZClpjIlHBvA2yD10ScXtJoDdprv41pfABniEvXjmd3Ue2VMyLjm/Pg+kll3G/cTaLgNLoNLeN7LmYz1hseQrzH5hbim3XrEgsHMRunKbeM23yJ7Bbn+88h9p6DIMYzce1v8gj5nuMjq+u7BeyH6erGJ96lV8YozHJIufnPv+mBjTBA0tioBfNwgqFbrwvffuIjFKR63fTjkLlfCIWgJgcF0kAoPr5ft5DlpJcY7svDkz89xKIlsk70sfCkJ6PE
  template:
    metadata:
      name: gami-secrets
      namespace: gami-dev
